// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by "ffi-gen".
/* tslint:disable */
/* eslint:disable */

/**
 * Main entry point to the library.
 */
export class Api {
  /**
   * API constructor.
   *
   * @returns an `Api` instance.
   */
  constructor();

  /**
   * Initialize the API.
   *
   * @returns a promise resolved when initialization is done.
   */
  fetch(url, imports): Promise<void>;

  createS(x: number, y: number): OurStruct;

  newStructList(): OurStructList;

  createSs(): OurStructList;

  printSs(ss: OurStructList): void;
}

export class OurStruct {
  print(): void;

  drop(): void;
}
export class OurStructList {
  add(s: OurStruct): void;

  print(): void;

  get(index: number): ?OurStruct;

  drop(): void;
}
