// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by "ffi-gen".
/* tslint:disable */
/* eslint:disable */

let fs;
const fetch_polyfill = async (file) => {
  const readFile = await eval("mport('fs')".replace(/^/, "i")).then(
    ({ readFile }) => readFile
  );
  return new Promise((resolve, reject) => {
    readFile(file, function (err, data) {
      return err
        ? reject(err)
        : resolve({
            arrayBuffer: () => Promise.resolve(data),
            ok: true,
          });
    });
  });
};

let ReadableStream;
if (typeof window == "object") {
  ReadableStream = window.ReadableStream;
  // Workaround for combined use with `wasm-bindgen`, so we don't have to
  // patch the `importObject` while loading the WASM module.
  window.__notifier_callback = (idx) => notifierRegistry.callbacks[idx]();
} else {
  eval("mport('node:stream/web')".replace(/^/, "i")).then((pkg) => {
    ReadableStream = pkg.ReadableStream;
  });
  // Workaround for combined use with `wasm-bindgen`, so we don't have to
  // patch the `importObject` while loading the WASM module.
  global.__notifier_callback = (idx) => notifierRegistry.callbacks[idx]();
}

const fetchFn = (typeof fetch === "function" && fetch) || fetch_polyfill;

function fetchAndInstantiate(url, imports) {
  const env = imports.env || {};
  env.__notifier_callback = (idx) => notifierRegistry.callbacks[idx]();
  imports.env = env;
  return fetchFn(url)
    .then((resp) => {
      if (!resp.ok) {
        throw new Error("Got a ${resp.status} fetching wasm @ ${url}");
      }

      const wasm = "application/wasm";
      const type = resp.headers && resp.headers.get("content-type");

      return WebAssembly.instantiateStreaming && type === wasm
        ? WebAssembly.instantiateStreaming(resp, imports)
        : resp
            .arrayBuffer()
            .then((buf) => WebAssembly.instantiate(buf, imports));
    })
    .then((result) => result.instance);
}

const dropRegistry = new FinalizationRegistry((drop) => drop());

class Box {
  constructor(ptr, destructor) {
    this.ptr = ptr;
    this.dropped = false;
    this.moved = false;
    dropRegistry.register(this, destructor, this);
    this.destructor = destructor;
  }

  borrow() {
    if (this.dropped) {
      throw new Error("use after free");
    }
    if (this.moved) {
      throw new Error("use after move");
    }
    return this.ptr;
  }

  move() {
    if (this.dropped) {
      throw new Error("use after free");
    }
    if (this.moved) {
      throw new Error("can't move value twice");
    }
    this.moved = true;
    dropRegistry.unregister(this);
    return this.ptr;
  }

  drop() {
    if (this.dropped) {
      throw new Error("double free");
    }
    if (this.moved) {
      throw new Error("can't drop moved value");
    }
    this.dropped = true;
    dropRegistry.unregister(this);
    this.destructor();
  }
}

class NotifierRegistry {
  constructor() {
    this.counter = 0;
    this.callbacks = {};
  }

  reserveSlot() {
    const idx = this.counter;
    this.counter += 1;
    return idx;
  }

  registerNotifier(idx, notifier) {
    this.callbacks[idx] = notifier;
  }

  unregisterNotifier(idx) {
    delete this.callbacks[idx];
  }
}

const notifierRegistry = new NotifierRegistry();

const nativeFuture = (box, nativePoll) => {
  const poll = (resolve, reject, idx) => {
    try {
      const ret = nativePoll(box.borrow(), 0, BigInt(idx));
      if (ret == null) {
        return;
      }
      resolve(ret);
    } catch (err) {
      reject(err);
    }
    notifierRegistry.unregisterNotifier(idx);
    box.drop();
  };
  return new Promise((resolve, reject) => {
    const idx = notifierRegistry.reserveSlot();
    const notifier = () => poll(resolve, reject, idx);
    notifierRegistry.registerNotifier(idx, notifier);
    poll(resolve, reject, idx);
  });
};

function* nativeIter(box, nxt) {
  let el;
  while (true) {
    el = nxt(box.borrow());
    if (el === null) {
      break;
    }
    yield el;
  }
  box.drop();
}

const nativeStream = (box, nativePoll) => {
  const poll = (next, nextIdx, doneIdx) => {
    const ret = nativePoll(box.borrow(), 0, BigInt(nextIdx), BigInt(doneIdx));
    if (ret != null) {
      next(ret);
    }
  };
  return new ReadableStream({
    start(controller) {
      const nextIdx = notifierRegistry.reserveSlot();
      const doneIdx = notifierRegistry.reserveSlot();
      const nextNotifier = () =>
        setTimeout(
          () => poll((x) => controller.enqueue(x), nextIdx, doneIdx),
          0
        );
      const doneNotifier = () => {
        notifierRegistry.unregisterNotifier(nextIdx);
        notifierRegistry.unregisterNotifier(doneIdx);
        controller.close();
        box.drop();
      };
      notifierRegistry.registerNotifier(nextIdx, nextNotifier);
      notifierRegistry.registerNotifier(doneIdx, doneNotifier);
      nextNotifier();
    },
  });
};

export class Api {
  async fetch(url, imports) {
    this.instance = await fetchAndInstantiate(url, imports);
  }

  initWithInstance(instance) {
    this.instance = instance;
  }

  allocate(size, align) {
    return this.instance.exports.allocate(size, align);
  }

  deallocate(ptr, size, align) {
    this.instance.exports.deallocate(ptr, size, align);
  }

  drop(symbol, ptr) {
    this.instance.exports[symbol](0, ptr);
  }

  getImage() {
    const tmp0 = this.instance.exports.__get_image();
    const tmp2 = tmp0;
    const tmp2_0 = () => {
      this.drop("drop_box_FfiBuffer", tmp2);
    };
    const tmp2_1 = new Box(tmp2, tmp2_0);
    const tmp3 = new FfiBuffer(this, tmp2_1);
    const tmp1 = tmp3;
    return tmp1;
  }
  create(n) {
    const tmp0 = n;
    let tmp1 = 0;
    tmp1 = tmp0;
    const tmp2 = this.instance.exports.__create(tmp1);
    const tmp4 = tmp2;
    const tmp4_0 = () => {
      this.drop("drop_box_DataTest", tmp4);
    };
    const tmp4_1 = new Box(tmp4, tmp4_0);
    const tmp3 = new DataTest(this, tmp4_1);
    return tmp3;
  }
}

export class DataTest {
  constructor(api, box) {
    this.api = api;
    this.box = box;
  }

  getCopy() {
    let tmp0 = 0;
    tmp0 = this.box.borrow();
    const tmp1 = this.api.instance.exports.__DataTest_get_copy(tmp0);
    const tmp3 = tmp1[0];
    const tmp4 = tmp1[1];
    const tmp5 = tmp1[2];
    const tmp2_0 = new Uint8Array(
      this.api.instance.exports.memory.buffer,
      tmp3,
      tmp4
    );
    const tmp2 = Array.from(tmp2_0);
    if (tmp5 > 0) {
      this.api.deallocate(tmp3, tmp5 * 4, 4);
    }
    return tmp2;
  }
  getShmem() {
    let tmp0 = 0;
    tmp0 = this.box.borrow();
    const tmp1 = this.api.instance.exports.__DataTest_get_shmem(tmp0);
    const tmp3 = tmp1;
    const tmp3_0 = () => {
      this.api.drop("drop_box_FfiBuffer", tmp3);
    };
    const tmp3_1 = new Box(tmp3, tmp3_0);
    const tmp4 = new FfiBuffer(this.api, tmp3_1);
    const tmp2 = tmp4;
    return tmp2;
  }

  drop() {
    this.box.drop();
  }
}

export default Api;
